// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb7TxH_7o9FhYQq1Z-Wi5-xegKNjq4QCo',
    appId: '1:136520438552:web:1b495f34a6cdafe807846d',
    messagingSenderId: '136520438552',
    projectId: 'facebook-clone-ui-e5c97',
    authDomain: 'facebook-clone-ui-e5c97.firebaseapp.com',
    storageBucket: 'facebook-clone-ui-e5c97.appspot.com',
    measurementId: 'G-HLM1GC4L2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSOnaPJtRfLixTnWBK-RlZSzXwR7tv9ic',
    appId: '1:136520438552:android:e4473b4394f762cb07846d',
    messagingSenderId: '136520438552',
    projectId: 'facebook-clone-ui-e5c97',
    storageBucket: 'facebook-clone-ui-e5c97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbZsFdC3kn29uc_rGjO1LLBvbvx58s5ck',
    appId: '1:136520438552:ios:0e4fdf5e6185bd6907846d',
    messagingSenderId: '136520438552',
    projectId: 'facebook-clone-ui-e5c97',
    storageBucket: 'facebook-clone-ui-e5c97.appspot.com',
    iosClientId: '136520438552-jl91hg1ud8t1j4h443q2iqqnvhmho2r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbZsFdC3kn29uc_rGjO1LLBvbvx58s5ck',
    appId: '1:136520438552:ios:0e4fdf5e6185bd6907846d',
    messagingSenderId: '136520438552',
    projectId: 'facebook-clone-ui-e5c97',
    storageBucket: 'facebook-clone-ui-e5c97.appspot.com',
    iosClientId: '136520438552-jl91hg1ud8t1j4h443q2iqqnvhmho2r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSample',
  );
}
